### ISSUE TITLE
您好，

### ISSUE THREAD

**Issue by ribuug** [SmacUL/HomeWork#1]
~

**Comment by SmacUL** [comment]
你说我 NewsRecommend 当中的东西？咨询就不必了吧，那个我都没写到推荐的部分，也不是很懂。

**Comment by ribuug** [comment]
好的，谢谢。

**Comment by 686id** [comment]
如果你要练手做一个简单的推荐站点，我们可以聊聊吗

**Comment by SmacUL** [comment]
> 如果你要练手做一个简单的推荐站点，我们可以聊聊吗

你是哪的？工作了还是学生？我这段时间可能事比较多

**Comment by ribuug** [comment]
好吧
